language: csharp
os:
  - linux
  - osx
dist: trusty
osx_image: xcode7.3
branches:
    only:
      - develop
      - master
mono:
  - none
addons:
  apt:
    packages:
      - gettext
      - libcurl4-openssl-dev
      - libicu-dev
      - libssl-dev
      - libunwind8
      - zlib1g
      - curl
before-install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update
      brew install jq
      brew install openssl
      ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
      ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
    fi
script: ./condo.sh -- /t:ci
