version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - develop
  - master
skip_tags: true
skip_branch_with_pr: true
skip_commits:
  message: '***NO_CI***'
image: Visual Studio 2017
environment:
  GH_TOKEN:
    secure: dQBV6ymcqDHOLzE1T5jWRs4863Uednt/Luj0pqghFo/G0c3hiGTVfNAbfFkt50up
  SKIP_NPM: true
  SKIP_POLYMER: true
  SKIP_BOWER: true
install:
- ps: Install-Product node lts
build_script:
- cmd: condo.cmd -Verbosity Diagnostic /t:ci /t:document
test: off
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/c731d7b3fd486219480c
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
