pull_requests:
  do_not_increment_build_number: true
branches:
  except:
  - /feature/*
  - /bugfix/*
  - /hotfix/*
  - /support/*
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2017
cache:
- '%USERPROFILE%\.nuget'
- '%USERPROFILE%\.am'
- '%LOCALAPPDATA%\Microsoft\dotnet'
build_script:
  - condo.cmd /t:ci
