version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - develop
  - master
skip_tags: true
skip_branch_with_pr: true
skip_commits:
  message: '***NO_CI***'
image: Visual Studio 2017
environment:
  GH_TOKEN:
    secure: HXDr0rstXSt8dsyX7xzWLlzcKCNxQQGPGyEoWv9Cu5eZMwe4T8wJm2K2qaVgcsQr
  CONDO_CREATE_RELEASE: true
install:
- ps: Install-Product node lts
build_script:
- cmd: condo.cmd /t:ci /t:document
test: off
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/c731d7b3fd486219480c
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
