version: 1.0.{build}
environment:
  nodejs_version: ''

pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - develop
    - master
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2017
install:
  - ps: Install-Product node $env:nodejs_version
build_script:
  - cmd: condo.cmd -- /t:ci
test: off
skip_commits:
  message: '***NO_CI***'
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/c731d7b3fd486219480c
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
