resources:
- repo: self
  clean: true

trigger:
- master
- develop

jobs:
- template: .azure/cli.yaml
  parameters:
    pool:
      name: kubernetes-agents
      demands:
      - condo
      - dotnet
