version: 2
jobs:
  condo:
    working_directory: /target
    docker:
      - image: automotivemastermind/condo:latest
        environment:
          SKIP_NPM: 'true'
          SKIP_BOWER: 'true'
          SKIP_POLYMER: 'true'
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run condo
          command: 'cd /condo && ./docker.sh condo -- /t:publish'

workflows:
  version: 2
  build_and_test:
    jobs:
    - condo
