parameters:
  name: condo
  verbosity: normal
  target: publish
  token: ''

jobs:
- job: ${{ parameters.name }}

  steps:
  - script: /usr/bin/condo --no-color --verbosity $CONDO_VERBOSITY -- /t:$CONDO_TARGET
    name: condo_execute
    displayName: execute condo
    continueOnError: true
    env:
      CONDO_VERBOSITY: ${{ parameters.verbosity }}
      CONDO_TARGET: ${{ parameters.target }}
      SYSTEM_ACCESSTOKEN: ${{ parameters.token }}

  - task: CopyFiles@2
    name: condo_copy_logs
    displayName: copy logs
    continueOnError: true
    inputs:
      SourceFolder: artifacts
      Contents: |
        *.log
        *.rsp
      TargetFolder: '$(build.artifactstagingdirectory)/logs'
      CleanTargetFolder: true
      OverWrite: true

  - task: PublishBuildArtifacts@1
    name: condo_push_logs
    continueOnError: true
    displayName: publish logs
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/logs'
      ArtifactName: Logs

  - task: PublishTestResults@2
    name: condo_push_tests
    displayName: publish test results
    continueOnError: true
    inputs:
      testRunner: VSTest
      testResultsFiles: 'artifacts/test/*.trx'
      mergeTestResults: true

  - task: PublishCodeCoverageResults@1
    name: condo_push_coverage
    displayName: publish code coverage results
    continueOnError: true
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: artifacts/test/coverage.xml
