parameters:
  name: condo
  verbosity: normal
  target: publish

jobs:
- job: ${{ parameters.name }}

  steps:
  - script: /usr/bin/condo --no-color --verbosity ${{ parameters.verbosity }} -- /t:target=${{ parameters.target }}
    name: condo_execute
    displayName: execute condo

  - task: CopyFiles@2
    name: condo_copy_logs
    displayName: copy logs
    inputs:
      SourceFolder: artifacts
      Contents: |
        *.log
        *.rsp
      TargetFolder: '$(build.artifactstagingdirectory)/logs'
      CleanTargetFolder: true
      OverWrite: true

  - task: PublishBuildArtifacts@1
    name: condo_push_logs
    displayName: publish logs
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/logs'
      ArtifactName: Logs

  - task: PublishTestResults@2
    name: condo_push_tests
    displayName: publish test results
    inputs:
      testRunner: VSTest
      testResultsFiles: 'artifacts/test/*.trx'
      mergeTestResults: true

  - task: PublishCodeCoverageResults@1
    name: condo_push_coverage
    displayName: publish code coverage results
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: artifacts/test/coverage.xml
