parameters:
  name: condo
  verbosity: normal
  target: publish
  pool: ''

jobs:
- job: ${{ parameters.name }}

pool:
  name: ${{ parameters.pool }}
  demands:
  - condo
  - dotnet1
  - dotnet2

  steps:
  - script: /usr/bin/condo --no-color --verbosity ${{ parameters.verbosity }} -- /t:target=${{ parameters.target }}
    name: execute condo

  - task: CopyFiles@2
    name: copy logs
    inputs:
      SourceFolder: artifacts
      Contents: |
      *.log
      *.rsp
      TargetFolder: '$(build.artifactstagingdirectory)/logs'
      CleanTargetFolder: true
      OverWrite: true

  - task: PublishBuildArtifacts@1
    name: publish logs
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/logs'
      ArtifactName: Logs

  - task: PublishTestResults@2
    name: publish test results
    inputs:
      testRunner: VSTest
      testResultsFiles: 'artifacts/test/*.trx'
      mergeTestResults: true

  - task: PublishCodeCoverageResults@1
    name: publish code coverage results
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: artifacts/test/coverage.xml
