parameters:
  name: condo
  verbosity: normal
  target: publish
  pool: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}

  steps:
  - name: execute_condo
    displayName: execute condo
    script: /usr/bin/condo --no-color --verbosity ${{ parameters.verbosity }} -- /t:target=${{ parameters.target }}

  - name: copy_logs
    displayName: copy logs
    task: CopyFiles@2
    inputs:
      SourceFolder: artifacts
      Contents: |
        *.log
        *.rsp
      TargetFolder: '$(build.artifactstagingdirectory)/logs'
      CleanTargetFolder: true
      OverWrite: true

  - name: publish_logs
    displayName: publish logs
    task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/logs'
      ArtifactName: Logs

  - name: publish_tests
    displayName: publish test results
    task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: 'artifacts/test/*.trx'
      mergeTestResults: true

  - name: publish_coverage
    displayName: publish code coverage results
    task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: artifacts/test/coverage.xml
